### ISSUE TITLE
Create GuttenbergReporter to flag plagiarism

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Userscripts#11]
It would be nice, if we could raise mod-flags with automatically generated text that includes a link to SOBotics/CopyPastor for flagging plagiarism and reposts*. The UI could be similar to NattyReporter, but with only four options:

* tp: Sends `@Guttenberg feedback [CopyPastor link] tp` in chat
* fp: Sends `@Guttenberg feedback [CopyPastor link] fp` in chat
* FLAG Plag: Flags with the text for plagiarism and sends `@Guttenberg feedback [CopyPastor link] tp` in chat
* FLAG Repost: Flags with the text for repost (not sure, if we should give feedback automatically in that case)*

### API to get the CopyPastor-link

See https://github.com/SOBotics/CopyPastor#post-or-get-postsfind

### Flag-text

We are currently discussing the flag-texts in SOBotics/Guttenberg#136.

----
<sub>* we only flag extreme reposters after we warned them. We don't flag, if the JW-score is 1.0, since that raises an auto-flag.</sub>

**Comment by Bhargav-Rao** [comment]
I don't see the reason to flag the extreme reposters. All of the reposted answers would raise an auto flag. You'll need to raise a flag _only when the reposts aren't a word to word match_.

**Comment by BaumMitAugen** [comment]
For flagging with _"the text for plagiarism/repost"_, we would need a way to query the original source from the report, wouldn't we?
Or do we just flag "That's a repost"? 

Also, we'd need to get the `[CopyPastor link]` somehow from the post id if we want to post that to chat. I guess we can query that from some CP API by giving it the post ID?

**Comment by rjrudman** [comment]
@Bhargav-Rao How strict is that check for automatic flags? Is it literally 100% text match? Or is there some leeway

**Comment by Bhargav-Rao** [comment]
@rjrudman It's a 100% text match. I've not seen any cases where there were any differences.

**Comment by Bhargav-Rao** [comment]
@BaumMitAugen Yeah, for that we would probably need another API endpoint from CP, like this one https://github.com/SOBotics/CopyPastor/issues/12, which would probably return something like this:

```
{
    "status":"success",
    "post_id":"cp post id",
    "target_url":"url of the original post"
}
```

**Comment by BaumMitAugen** [comment]
Is this still relevant or is this made obsolete by Advanced Flagging? @FelixSFD

**Comment by FelixSFD** [comment]
I think it's obsolete now
