### ISSUE TITLE
Should we stop using VLQ?

### ISSUE THREAD

**Issue by jdd-software** [SOBotics/Userscripts#12]
The VLQ is a strange flag that sometimes does not desired stuff (it get's cleared by OP when it should not, it auto down-votes even if good edit). 

Should we stop using this flag? (hence change also in Natty Reporter?).

Do note that link only answer by Shog9 are considered NAA see https://meta.stackexchange.com/questions/225370/your-answer-is-in-another-castle-when-is-an-answer-not-an-answer

> So let me be clear: this sort of response is not an answer. 

and since we have Generic bot tracking edits the feature of auto-clearing flags are just a mess. 

Furthermore we do know that mods do not make any difference between these flags (lost of meta posts, including Tuna's FR)

For some discussion in chat see from https://chat.stackoverflow.com/transcript/message/40943898#40943898

**Comment by FelixSFD** [comment]
I like the VLQ-flags for link-only answers. Since we leave a comment, many users are improving their answer which clears the flag. Flagging NAA raises the chance of getting a declined flag, even with Generic Bot

**Comment by jdd-software** [comment]
@FelixSFD but if they improve you also leave a downvote?  I almost prefer declined flag then the system leaving down votes on stuff that maybe I can't even judge

**Comment by FelixSFD** [comment]
@jdd-software I don't downvote many link-only posts. Only when the user edits it without improving it

**Comment by jdd-software** [comment]
@FelixSFD hmm?, the community user downvote it for you if you flag VLQ and they edit.... That is what I mean, I don't like that effect.

**Comment by GrumpyCrouton** [comment]
@jdd-software Wait, that doesn't make sense to me. Why would it auto downvote a question just because it was flagged at VLQ and it was edited? Wouldn't you assume that when OP edits a VLQ post that it would become _better_?

**Comment by BaumMitAugen** [comment]
@jdd-software I've never heard of that auto downvote and thus never considered it as a factor in this discussion.

Without taking that into account, I do like the VLQ flag for LO. Fixed VLQ-posts are [not exactly rare](https://chat.stackoverflow.com/search?q=untrack&room=111347).

Iirc, the original version by Nobody Nada used to NAA flag everything, which promptly left me with disputed flag due to an edit, which also happened to Floern I think, so I changed it to VLQ.

~I think we should keep it.~ Just learned how that auto-downvote works, not so sure anymore. For the flagger, VLQ is more convenient, but leaving around down-votes on stuff I don't understand does not really feel right...

**Comment by jdd-software** [comment]
https://meta.stackexchange.com/questions/236883/community-downvotes-posts-that-were-just-fixed?noredirect=1&lq=1

crazy or not crazy that is how it works

**Comment by Floern** [comment]
I'll stick to the VLQ flag, _because_ it gets cleared on an edit. I don't care much about the auto-downvote. Sure, it's somewhat off when the post is significantly improved, but I can revert that with an upvote. And if the post is still bad it gets one more downvote.

In the end it's up to you what flag you use.

**Comment by GrumpyCrouton** [comment]
I think the issue that @jdd-software mentions is really a non-issue, as Shog9 said in the answer on the post that jdd posted:

> The system will now revoke the automatic downvote if, after the flag is marked Helpful, the post later gets an upvote.
https://meta.stackexchange.com/a/266436/360627

In that case, I say that we should keep the VLQ flag. I don't think any other flag really makes sense.

**Comment by jdd-software** [comment]
Since we have different ideas, my conclusion is that there is no current need to modify the userscript globally (single users can easily change this [line](https://github.com/SOBotics/Userscripts/blob/master/Natty/NattyReporter.user.js#L168) according to their preference). 

If in the future a config dialog is built into the script, this issue can be considered.

**Comment by mogsdad** [comment]
NEW INFO - the VLQ flag has disappeared, so Natty is now broken. Can't report "Link-Only".
