### ISSUE TITLE
Stack Exchange Flag Tracker is not searchable

### ISSUE THREAD

**Issue by tripleee** [SOBotics/Userscripts#15]
This is the name I see in TamperMonkey but it doesn't seem to be exposed anywhere else. I'm _guessing_ this is flagtracker.js but the challenge here is precisely being able to find authoritatively that I am actually looking at the correct script. {Perhaps I am merely exposing my incomplete understanding of userscript technology.)

**Comment by Floern** [comment]
I moved the script to https://github.com/Floern/stackoverflow/blob/master/userscripts/flagtracker.user.js -- The one here in the SOBotics repository is an old version and refers to the new repository in its `@updateUrl`.
