### ISSUE TITLE
Natty feedback from NATO queue

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/Userscripts#9]
Would anyone be interested in having feedback controls from within the NATO queue? I'd imagine it'd look something like:

![](http://i.imgur.com/ka0xCt5.png)

Thoughts?

**Comment by double-fault** [comment]
Well, I have no experience in userscripts, but I've pinged a person who _should_ be able to do this.

**Comment by rjrudman** [comment]
I'd be happy to implement it, just looking for feedback from users if it's something they'd like to see included

**Comment by rjrudman** [comment]
I've got it all working. If someone wants to give it a try, it's here: https://github.com/rjrudman/Userscripts

However, I'm not too happy with the fact that we don't have information about the comments on the post (or status with Natty, if it's already reported). This may lead to people doubling up on comments. I'll submit a pull request once I can figure out how to nicely solve this problem.

**Comment by Floern** [comment]
I'm using the [NATOEnhancements](https://github.com/Tiny-Giant/myuserscripts/blob/master/NATOEnhancements.user.js) script for this. It loads basically the complete answer and thus has implicit support for Natty controls. And you see the comments too.

![unbenannt](https://user-images.githubusercontent.com/2777643/28957349-c7e23f68-78f1-11e7-8c8a-b02ed8266b9c.png)

So I'm not sure if it's worth implementing it (again).

**Comment by rjrudman** [comment]
Hadn't noticed that script before. I agree, with that around, there isn't much sense in modifying the script for NATO.
